version: '3'

services:
  spring:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: spring
      volumes:
         - ./:/usr/src/myapp
      ports:
         - 8080:8080
  mysql:
      image: mysql:8
      container_name: mysql-test
      environment: 
          MYSQL_DATABASE: pruebaspring
          MYSQL_ROOT_PASSWORD: root
      ports:
          - "3306:3306"
      restart: always